name: Build and upload release to Github

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.

jobs:
  build:
    name: Build and upload release to Github
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      
      - name: Create windows executable
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: "."
          spec: "rowing.spec"

      - name: Copy windows executable files
        run: cp -r dist/windows/rowing ./

      - name: Zip windows executable
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist/rowing.zip rowing

      - uses: actions/upload-artifact@v2
        with:
          name: rowing-windows
          path: ./dist/windows # or path/to/artifact

      - name: Release
        if: contains(github.ref, 'tags/v')
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

